/*
 * This file is subject to the terms and conditions of the GNU General Public
 * License.  See the file "COPYING" in the main directory of this archive
 * for more details.
 *
 * Copyright (C) 1995, 96, 97, 98, 99, 2000 by Ralf Baechle
 *
 * Changed system calls macros _syscall5 - _syscall7 to push args 5 to 7 onto
 * the stack. Robin Farine for ACN S.A, Copyright (C) 1996 by ACN S.A
 */

/*
 * This used to be unistd.h, but it was too much.
 *
 * Modified 2006 by Kenneth Arnold (kca5) to change prefix to
 * __mipseb_linux_ to avoid collision with the native symbols.
 */

#ifndef _MIPS_LINUX_SYSCALLS_H
#define _MIPS_LINUX_SYSCALLS_H

#define __mipseb_linux_Linux			4000
#define __mipseb_linux_syscall			(__mipseb_linux_Linux +   0)
#define __mipseb_linux_exit			(__mipseb_linux_Linux +   1)
#define __mipseb_linux_fork			(__mipseb_linux_Linux +   2)
#define __mipseb_linux_read			(__mipseb_linux_Linux +   3)
#define __mipseb_linux_write			(__mipseb_linux_Linux +   4)
#define __mipseb_linux_open			(__mipseb_linux_Linux +   5)
#define __mipseb_linux_close			(__mipseb_linux_Linux +   6)
#define __mipseb_linux_waitpid			(__mipseb_linux_Linux +   7)
#define __mipseb_linux_creat			(__mipseb_linux_Linux +   8)
#define __mipseb_linux_link			(__mipseb_linux_Linux +   9)
#define __mipseb_linux_unlink			(__mipseb_linux_Linux +  10)
#define __mipseb_linux_execve			(__mipseb_linux_Linux +  11)
#define __mipseb_linux_chdir			(__mipseb_linux_Linux +  12)
#define __mipseb_linux_time			(__mipseb_linux_Linux +  13)
#define __mipseb_linux_mknod			(__mipseb_linux_Linux +  14)
#define __mipseb_linux_chmod			(__mipseb_linux_Linux +  15)
#define __mipseb_linux_lchown			(__mipseb_linux_Linux +  16)
#define __mipseb_linux_break			(__mipseb_linux_Linux +  17)
#define __mipseb_linux_oldstat			(__mipseb_linux_Linux +  18)
#define __mipseb_linux_lseek			(__mipseb_linux_Linux +  19)
#define __mipseb_linux_getpid			(__mipseb_linux_Linux +  20)
#define __mipseb_linux_mount			(__mipseb_linux_Linux +  21)
#define __mipseb_linux_umount			(__mipseb_linux_Linux +  22)
#define __mipseb_linux_setuid			(__mipseb_linux_Linux +  23)
#define __mipseb_linux_getuid			(__mipseb_linux_Linux +  24)
#define __mipseb_linux_stime			(__mipseb_linux_Linux +  25)
#define __mipseb_linux_ptrace			(__mipseb_linux_Linux +  26)
#define __mipseb_linux_alarm			(__mipseb_linux_Linux +  27)
#define __mipseb_linux_oldfstat			(__mipseb_linux_Linux +  28)
#define __mipseb_linux_pause			(__mipseb_linux_Linux +  29)
#define __mipseb_linux_utime			(__mipseb_linux_Linux +  30)
#define __mipseb_linux_stty			(__mipseb_linux_Linux +  31)
#define __mipseb_linux_gtty			(__mipseb_linux_Linux +  32)
#define __mipseb_linux_access			(__mipseb_linux_Linux +  33)
#define __mipseb_linux_nice			(__mipseb_linux_Linux +  34)
#define __mipseb_linux_ftime			(__mipseb_linux_Linux +  35)
#define __mipseb_linux_sync			(__mipseb_linux_Linux +  36)
#define __mipseb_linux_kill			(__mipseb_linux_Linux +  37)
#define __mipseb_linux_rename			(__mipseb_linux_Linux +  38)
#define __mipseb_linux_mkdir			(__mipseb_linux_Linux +  39)
#define __mipseb_linux_rmdir			(__mipseb_linux_Linux +  40)
#define __mipseb_linux_dup			(__mipseb_linux_Linux +  41)
#define __mipseb_linux_pipe			(__mipseb_linux_Linux +  42)
#define __mipseb_linux_times			(__mipseb_linux_Linux +  43)
#define __mipseb_linux_prof			(__mipseb_linux_Linux +  44)
#define __mipseb_linux_brk			(__mipseb_linux_Linux +  45)
#define __mipseb_linux_setgid			(__mipseb_linux_Linux +  46)
#define __mipseb_linux_getgid			(__mipseb_linux_Linux +  47)
#define __mipseb_linux_signal			(__mipseb_linux_Linux +  48)
#define __mipseb_linux_geteuid			(__mipseb_linux_Linux +  49)
#define __mipseb_linux_getegid			(__mipseb_linux_Linux +  50)
#define __mipseb_linux_acct			(__mipseb_linux_Linux +  51)
#define __mipseb_linux_umount2			(__mipseb_linux_Linux +  52)
#define __mipseb_linux_lock			(__mipseb_linux_Linux +  53)
#define __mipseb_linux_ioctl			(__mipseb_linux_Linux +  54)
#define __mipseb_linux_fcntl			(__mipseb_linux_Linux +  55)
#define __mipseb_linux_mpx			(__mipseb_linux_Linux +  56)
#define __mipseb_linux_setpgid			(__mipseb_linux_Linux +  57)
#define __mipseb_linux_ulimit			(__mipseb_linux_Linux +  58)
#define __mipseb_linux_unused59			(__mipseb_linux_Linux +  59)
#define __mipseb_linux_umask			(__mipseb_linux_Linux +  60)
#define __mipseb_linux_chroot			(__mipseb_linux_Linux +  61)
#define __mipseb_linux_ustat			(__mipseb_linux_Linux +  62)
#define __mipseb_linux_dup2			(__mipseb_linux_Linux +  63)
#define __mipseb_linux_getppid			(__mipseb_linux_Linux +  64)
#define __mipseb_linux_getpgrp			(__mipseb_linux_Linux +  65)
#define __mipseb_linux_setsid			(__mipseb_linux_Linux +  66)
#define __mipseb_linux_sigaction			(__mipseb_linux_Linux +  67)
#define __mipseb_linux_sgetmask			(__mipseb_linux_Linux +  68)
#define __mipseb_linux_ssetmask			(__mipseb_linux_Linux +  69)
#define __mipseb_linux_setreuid			(__mipseb_linux_Linux +  70)
#define __mipseb_linux_setregid			(__mipseb_linux_Linux +  71)
#define __mipseb_linux_sigsuspend			(__mipseb_linux_Linux +  72)
#define __mipseb_linux_sigpending			(__mipseb_linux_Linux +  73)
#define __mipseb_linux_sethostname		(__mipseb_linux_Linux +  74)
#define __mipseb_linux_setrlimit			(__mipseb_linux_Linux +  75)
#define __mipseb_linux_getrlimit			(__mipseb_linux_Linux +  76)
#define __mipseb_linux_getrusage			(__mipseb_linux_Linux +  77)
#define __mipseb_linux_gettimeofday		(__mipseb_linux_Linux +  78)
#define __mipseb_linux_settimeofday		(__mipseb_linux_Linux +  79)
#define __mipseb_linux_getgroups			(__mipseb_linux_Linux +  80)
#define __mipseb_linux_setgroups			(__mipseb_linux_Linux +  81)
#define __mipseb_linux_reserved82			(__mipseb_linux_Linux +  82)
#define __mipseb_linux_symlink			(__mipseb_linux_Linux +  83)
#define __mipseb_linux_oldlstat			(__mipseb_linux_Linux +  84)
#define __mipseb_linux_readlink			(__mipseb_linux_Linux +  85)
#define __mipseb_linux_uselib			(__mipseb_linux_Linux +  86)
#define __mipseb_linux_swapon			(__mipseb_linux_Linux +  87)
#define __mipseb_linux_reboot			(__mipseb_linux_Linux +  88)
#define __mipseb_linux_readdir			(__mipseb_linux_Linux +  89)
#define __mipseb_linux_mmap			(__mipseb_linux_Linux +  90)
#define __mipseb_linux_munmap			(__mipseb_linux_Linux +  91)
#define __mipseb_linux_truncate			(__mipseb_linux_Linux +  92)
#define __mipseb_linux_ftruncate			(__mipseb_linux_Linux +  93)
#define __mipseb_linux_fchmod			(__mipseb_linux_Linux +  94)
#define __mipseb_linux_fchown			(__mipseb_linux_Linux +  95)
#define __mipseb_linux_getpriority		(__mipseb_linux_Linux +  96)
#define __mipseb_linux_setpriority		(__mipseb_linux_Linux +  97)
#define __mipseb_linux_profil			(__mipseb_linux_Linux +  98)
#define __mipseb_linux_statfs			(__mipseb_linux_Linux +  99)
#define __mipseb_linux_fstatfs			(__mipseb_linux_Linux + 100)
#define __mipseb_linux_ioperm			(__mipseb_linux_Linux + 101)
#define __mipseb_linux_socketcall			(__mipseb_linux_Linux + 102)
#define __mipseb_linux_syslog			(__mipseb_linux_Linux + 103)
#define __mipseb_linux_setitimer			(__mipseb_linux_Linux + 104)
#define __mipseb_linux_getitimer			(__mipseb_linux_Linux + 105)
#define __mipseb_linux_stat			(__mipseb_linux_Linux + 106)
#define __mipseb_linux_lstat			(__mipseb_linux_Linux + 107)
#define __mipseb_linux_fstat			(__mipseb_linux_Linux + 108)
#define __mipseb_linux_unused109			(__mipseb_linux_Linux + 109)
#define __mipseb_linux_iopl			(__mipseb_linux_Linux + 110)
#define __mipseb_linux_vhangup			(__mipseb_linux_Linux + 111)
#define __mipseb_linux_idle			(__mipseb_linux_Linux + 112)
#define __mipseb_linux_vm86			(__mipseb_linux_Linux + 113)
#define __mipseb_linux_wait4			(__mipseb_linux_Linux + 114)
#define __mipseb_linux_swapoff			(__mipseb_linux_Linux + 115)
#define __mipseb_linux_sysinfo			(__mipseb_linux_Linux + 116)
#define __mipseb_linux_ipc			(__mipseb_linux_Linux + 117)
#define __mipseb_linux_fsync			(__mipseb_linux_Linux + 118)
#define __mipseb_linux_sigreturn			(__mipseb_linux_Linux + 119)
#define __mipseb_linux_clone			(__mipseb_linux_Linux + 120)
#define __mipseb_linux_setdomainname		(__mipseb_linux_Linux + 121)
#define __mipseb_linux_uname			(__mipseb_linux_Linux + 122)
#define __mipseb_linux_modify_ldt			(__mipseb_linux_Linux + 123)
#define __mipseb_linux_adjtimex			(__mipseb_linux_Linux + 124)
#define __mipseb_linux_mprotect			(__mipseb_linux_Linux + 125)
#define __mipseb_linux_sigprocmask		(__mipseb_linux_Linux + 126)
#define __mipseb_linux_create_module		(__mipseb_linux_Linux + 127)
#define __mipseb_linux_init_module		(__mipseb_linux_Linux + 128)
#define __mipseb_linux_delete_module		(__mipseb_linux_Linux + 129)
#define __mipseb_linux_get_kernel_syms		(__mipseb_linux_Linux + 130)
#define __mipseb_linux_quotactl			(__mipseb_linux_Linux + 131)
#define __mipseb_linux_getpgid			(__mipseb_linux_Linux + 132)
#define __mipseb_linux_fchdir			(__mipseb_linux_Linux + 133)
#define __mipseb_linux_bdflush			(__mipseb_linux_Linux + 134)
#define __mipseb_linux_sysfs			(__mipseb_linux_Linux + 135)
#define __mipseb_linux_personality		(__mipseb_linux_Linux + 136)
#define __mipseb_linux_afs_syscall		(__mipseb_linux_Linux + 137) /* Syscall for Andrew File System */
#define __mipseb_linux_setfsuid			(__mipseb_linux_Linux + 138)
#define __mipseb_linux_setfsgid			(__mipseb_linux_Linux + 139)
#define __mipseb_linux__llseek			(__mipseb_linux_Linux + 140)
#define __mipseb_linux_getdents			(__mipseb_linux_Linux + 141)
#define __mipseb_linux__newselect			(__mipseb_linux_Linux + 142)
#define __mipseb_linux_flock			(__mipseb_linux_Linux + 143)
#define __mipseb_linux_msync			(__mipseb_linux_Linux + 144)
#define __mipseb_linux_readv			(__mipseb_linux_Linux + 145)
#define __mipseb_linux_writev			(__mipseb_linux_Linux + 146)
#define __mipseb_linux_cacheflush			(__mipseb_linux_Linux + 147)
#define __mipseb_linux_cachectl			(__mipseb_linux_Linux + 148)
#define __mipseb_linux_sysmips			(__mipseb_linux_Linux + 149)
#define __mipseb_linux_unused150			(__mipseb_linux_Linux + 150)
#define __mipseb_linux_getsid			(__mipseb_linux_Linux + 151)
#define __mipseb_linux_fdatasync			(__mipseb_linux_Linux + 152)
#define __mipseb_linux__sysctl			(__mipseb_linux_Linux + 153)
#define __mipseb_linux_mlock			(__mipseb_linux_Linux + 154)
#define __mipseb_linux_munlock			(__mipseb_linux_Linux + 155)
#define __mipseb_linux_mlockall			(__mipseb_linux_Linux + 156)
#define __mipseb_linux_munlockall			(__mipseb_linux_Linux + 157)
#define __mipseb_linux_sched_setparam		(__mipseb_linux_Linux + 158)
#define __mipseb_linux_sched_getparam		(__mipseb_linux_Linux + 159)
#define __mipseb_linux_sched_setscheduler		(__mipseb_linux_Linux + 160)
#define __mipseb_linux_sched_getscheduler		(__mipseb_linux_Linux + 161)
#define __mipseb_linux_sched_yield		(__mipseb_linux_Linux + 162)
#define __mipseb_linux_sched_get_priority_max	(__mipseb_linux_Linux + 163)
#define __mipseb_linux_sched_get_priority_min	(__mipseb_linux_Linux + 164)
#define __mipseb_linux_sched_rr_get_interval	(__mipseb_linux_Linux + 165)
#define __mipseb_linux_nanosleep			(__mipseb_linux_Linux + 166)
#define __mipseb_linux_mremap			(__mipseb_linux_Linux + 167)
#define __mipseb_linux_accept			(__mipseb_linux_Linux + 168)
#define __mipseb_linux_bind			(__mipseb_linux_Linux + 169)
#define __mipseb_linux_connect			(__mipseb_linux_Linux + 170)
#define __mipseb_linux_getpeername		(__mipseb_linux_Linux + 171)
#define __mipseb_linux_getsockname		(__mipseb_linux_Linux + 172)
#define __mipseb_linux_getsockopt			(__mipseb_linux_Linux + 173)
#define __mipseb_linux_listen			(__mipseb_linux_Linux + 174)
#define __mipseb_linux_recv			(__mipseb_linux_Linux + 175)
#define __mipseb_linux_recvfrom			(__mipseb_linux_Linux + 176)
#define __mipseb_linux_recvmsg			(__mipseb_linux_Linux + 177)
#define __mipseb_linux_send			(__mipseb_linux_Linux + 178)
#define __mipseb_linux_sendmsg			(__mipseb_linux_Linux + 179)
#define __mipseb_linux_sendto			(__mipseb_linux_Linux + 180)
#define __mipseb_linux_setsockopt			(__mipseb_linux_Linux + 181)
#define __mipseb_linux_shutdown			(__mipseb_linux_Linux + 182)
#define __mipseb_linux_socket			(__mipseb_linux_Linux + 183)
#define __mipseb_linux_socketpair			(__mipseb_linux_Linux + 184)
#define __mipseb_linux_setresuid			(__mipseb_linux_Linux + 185)
#define __mipseb_linux_getresuid			(__mipseb_linux_Linux + 186)
#define __mipseb_linux_query_module		(__mipseb_linux_Linux + 187)
#define __mipseb_linux_poll			(__mipseb_linux_Linux + 188)
#define __mipseb_linux_nfsservctl			(__mipseb_linux_Linux + 189)
#define __mipseb_linux_setresgid			(__mipseb_linux_Linux + 190)
#define __mipseb_linux_getresgid			(__mipseb_linux_Linux + 191)
#define __mipseb_linux_prctl			(__mipseb_linux_Linux + 192)
#define __mipseb_linux_rt_sigreturn		(__mipseb_linux_Linux + 193)
#define __mipseb_linux_rt_sigaction		(__mipseb_linux_Linux + 194)
#define __mipseb_linux_rt_sigprocmask		(__mipseb_linux_Linux + 195)
#define __mipseb_linux_rt_sigpending		(__mipseb_linux_Linux + 196)
#define __mipseb_linux_rt_sigtimedwait		(__mipseb_linux_Linux + 197)
#define __mipseb_linux_rt_sigqueueinfo		(__mipseb_linux_Linux + 198)
#define __mipseb_linux_rt_sigsuspend		(__mipseb_linux_Linux + 199)
#define __mipseb_linux_pread			(__mipseb_linux_Linux + 200)
#define __mipseb_linux_pwrite			(__mipseb_linux_Linux + 201)
#define __mipseb_linux_chown			(__mipseb_linux_Linux + 202)
#define __mipseb_linux_getcwd			(__mipseb_linux_Linux + 203)
#define __mipseb_linux_capget			(__mipseb_linux_Linux + 204)
#define __mipseb_linux_capset			(__mipseb_linux_Linux + 205)
#define __mipseb_linux_sigaltstack		(__mipseb_linux_Linux + 206)
#define __mipseb_linux_sendfile			(__mipseb_linux_Linux + 207)
#define __mipseb_linux_getpmsg			(__mipseb_linux_Linux + 208)
#define __mipseb_linux_putpmsg			(__mipseb_linux_Linux + 209)
#define __mipseb_linux_mmap2			(__mipseb_linux_Linux + 210)
#define __mipseb_linux_truncate64			(__mipseb_linux_Linux + 211)
#define __mipseb_linux_ftruncate64		(__mipseb_linux_Linux + 212)
#define __mipseb_linux_stat64			(__mipseb_linux_Linux + 213)
#define __mipseb_linux_lstat64			(__mipseb_linux_Linux + 214)
#define __mipseb_linux_fstat64			(__mipseb_linux_Linux + 215)
#define __mipseb_linux_pivot_root			(__mipseb_linux_Linux + 216)
#define __mipseb_linux_mincore			(__mipseb_linux_Linux + 217)
#define __mipseb_linux_madvise			(__mipseb_linux_Linux + 218)
#define __mipseb_linux_getdents64			(__mipseb_linux_Linux + 219)
#define __mipseb_linux_fcntl64			(__mipseb_linux_Linux + 220)

/*
 * Offset of the last Linux flavoured syscall
 */
#define __mipseb_linux_Linux_syscalls		220


#endif /* _MIPS_LINUX_SYSCALLS_H */
