name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Install Z3
      uses: pavpanchekha/setup-z3@1.2.2
    - name: Install Deps
      run: sudo apt-get install gperf
    - name: make
      run: make && make install
    - name: make test
      run: make test
